# Configurations
title:            Himanshu Shankar
longtitle:        Himanshu Shankar - Don't ask for LinkedIn please
author:           Himanshu Shankar
email:            reach@himanshus.com
description: >
  Himanshu's homepage based on Jekyll Gitbook. Needs update and some work, but he's too busy to update this. Also, he wants to get off all social network but people keep on asking his LinkedIn. So maybe, this will save him.

url:              'https://iamhssingh.github.io'

remote_theme:     sighingnow/jekyll-gitbook

social:
  github:         iamhssingh
